/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccessRouteImport } from './routes/_app/access'
import { Route as AppAskRouteImport } from './routes/_app/ask'
import { Route as AppCoverageRouteImport } from './routes/_app/coverage'
import { Route as AppGuidesRouteImport } from './routes/_app/guides'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppMeRouteImport } from './routes/_app/me'
import { Route as AppOrgsRouteImport } from './routes/_app/orgs'
import { Route as AppLibraryIndexRouteImport } from './routes/_app/library.index'
import { Route as AppLibraryPolicyIdRouteImport } from './routes/_app/library.$policyId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessRoute = AppAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AppRoute,
} as any)
const AppAskRoute = AppAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AppRoute,
} as any)
const AppCoverageRoute = AppCoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => AppRoute,
} as any)
const AppGuidesRoute = AppGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgsRoute = AppOrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryIndexRoute = AppLibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLibraryRoute,
} as any)
const AppLibraryPolicyIdRoute = AppLibraryPolicyIdRouteImport.update({
  id: '/$policyId',
  path: '/$policyId',
  getParentRoute: () => AppLibraryRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/access': typeof AppAccessRoute
  '/ask': typeof AppAskRoute
  '/coverage': typeof AppCoverageRoute
  '/guides': typeof AppGuidesRoute
  '/library': typeof AppLibraryRouteWithChildren
  '/me': typeof AppMeRoute
  '/orgs': typeof AppOrgsRoute
  '/library/$policyId': typeof AppLibraryPolicyIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/library/': typeof AppLibraryIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/access': typeof AppAccessRoute
  '/ask': typeof AppAskRoute
  '/coverage': typeof AppCoverageRoute
  '/guides': typeof AppGuidesRoute
  '/me': typeof AppMeRoute
  '/orgs': typeof AppOrgsRoute
  '/': typeof AppIndexRoute
  '/library/$policyId': typeof AppLibraryPolicyIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/library': typeof AppLibraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/access': typeof AppAccessRoute
  '/_app/ask': typeof AppAskRoute
  '/_app/coverage': typeof AppCoverageRoute
  '/_app/guides': typeof AppGuidesRoute
  '/_app/library': typeof AppLibraryRouteWithChildren
  '/_app/me': typeof AppMeRoute
  '/_app/orgs': typeof AppOrgsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/library/$policyId': typeof AppLibraryPolicyIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/library/': typeof AppLibraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/access'
    | '/ask'
    | '/coverage'
    | '/guides'
    | '/library'
    | '/me'
    | '/orgs'
    | '/library/$policyId'
    | '/api/auth/$'
    | '/library/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/access'
    | '/ask'
    | '/coverage'
    | '/guides'
    | '/me'
    | '/orgs'
    | '/'
    | '/library/$policyId'
    | '/api/auth/$'
    | '/library'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/access'
    | '/_app/ask'
    | '/_app/coverage'
    | '/_app/guides'
    | '/_app/library'
    | '/_app/me'
    | '/_app/orgs'
    | '/_app/'
    | '/_app/library/$policyId'
    | '/api/auth/$'
    | '/_app/library/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access': {
      id: '/_app/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AppAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ask': {
      id: '/_app/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AppAskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coverage': {
      id: '/_app/coverage'
      path: '/coverage'
      fullPath: '/coverage'
      preLoaderRoute: typeof AppCoverageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guides': {
      id: '/_app/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof AppGuidesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orgs': {
      id: '/_app/orgs'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof AppOrgsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library/': {
      id: '/_app/library/'
      path: '/'
      fullPath: '/library/'
      preLoaderRoute: typeof AppLibraryIndexRouteImport
      parentRoute: typeof AppLibraryRoute
    }
    '/_app/library/$policyId': {
      id: '/_app/library/$policyId'
      path: '/$policyId'
      fullPath: '/library/$policyId'
      preLoaderRoute: typeof AppLibraryPolicyIdRouteImport
      parentRoute: typeof AppLibraryRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppLibraryRouteChildren {
  AppLibraryPolicyIdRoute: typeof AppLibraryPolicyIdRoute
  AppLibraryIndexRoute: typeof AppLibraryIndexRoute
}

const AppLibraryRouteChildren: AppLibraryRouteChildren = {
  AppLibraryPolicyIdRoute: AppLibraryPolicyIdRoute,
  AppLibraryIndexRoute: AppLibraryIndexRoute,
}

const AppLibraryRouteWithChildren = AppLibraryRoute._addFileChildren(
  AppLibraryRouteChildren,
)

interface AppRouteChildren {
  AppAccessRoute: typeof AppAccessRoute
  AppAskRoute: typeof AppAskRoute
  AppCoverageRoute: typeof AppCoverageRoute
  AppGuidesRoute: typeof AppGuidesRoute
  AppLibraryRoute: typeof AppLibraryRouteWithChildren
  AppMeRoute: typeof AppMeRoute
  AppOrgsRoute: typeof AppOrgsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccessRoute: AppAccessRoute,
  AppAskRoute: AppAskRoute,
  AppCoverageRoute: AppCoverageRoute,
  AppGuidesRoute: AppGuidesRoute,
  AppLibraryRoute: AppLibraryRouteWithChildren,
  AppMeRoute: AppMeRoute,
  AppOrgsRoute: AppOrgsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
